### ISSUE TITLE
'Repost' doesn't pull content from tweet when reposting

### ISSUE THREAD

**Issue by egoexpress** [kylewm/KnownReactions#12]
I try to use the repost function via a bookmarklet to repost tweets on my Known site (and push the reposts to Twitter afterwards so they show up there natively).

The latter one works, but the display of the reposted tweet on my site is somewhat broken. See example at https://known.stierand.org/2016/06/repost-of-joschi-kuphal-%E5%90%89s-tweet-0842aea869.

It seems that the repost doesn't extract the content of the tweet properly. I guess it is supposed to do so as there is a 'body' section showing up on the repost page. In my instance it is empty, though.

The webserver log doesn't show any errors.

Known version: 0.9.2
Plugin version: 0.1.4 (pulled from GitHub some days ago)

**Comment by kylewm** [comment]
Thanks for the heads up. I'm using https://github.com/indieweb/php-mf2-shim to fill in the body text (which scrapes it from the Twitter HTML). It may be that the scraping assumptions finally broke down :(

**Comment by kylewm** [comment]
It seems to be working for me in general. 

Can you point me to the tweet you tried to repost that failed for you?

![screenshot from 2016-06-11 10-41-52](https://cloud.githubusercontent.com/assets/950127/15986636/34b0c3ba-2fc1-11e6-8ced-e3f94b9f454c.png)

**Comment by egoexpress** [comment]
I tried to use the following tweet:

https://twitter.com/JustHadOneJob/status/740769199941902336

I tried to repost it on my own site using the Known bookmarklet. The resulting post is at 

https://known.stierand.org/2016/06/repost-of-you-had-one-jobs-tweet-d03cd1d87b

However, the content looks blank/broken.

**Comment by kylewm** [comment]
Hmm, yeah I'm still at a loss... that posted fine for me https://known.kylewm.com/2016/06/repost-of-you-had-one-jobs-tweet-d03cd1d87b

So here's how the plugin works: you open with a bookmarklet (e.g. https://known.kylewm.com/share?share_type=repost&share_url=https://twitter.com/JustHadOneJob/status/740769199941902336), and then it fetches the tweet and parses out the content, and pre-fills it as the body of your post. 

<img width="835" alt="screen shot 2016-06-15 at 4 16 02 pm" src="https://cloud.githubusercontent.com/assets/950127/16100634/81f0eed8-3314-11e6-9511-013418a5d39c.png">


It takes 1-5 seconds for this to happen for me. This all has to happen *before* you click "Publish", or the post will be blank. It may just be that you are hitting publish before it gets filled in.

**Comment by egoexpress** [comment]
Seems I found the culprit. After looking at your screenshot and seeing the editor window I realized that I enabled the [Markdown plugin](https://github.com/idno/Markdown) which disables the rich text editor.

Disabling this plugin now shows the body as expected (as seen in your screenshot).

**Comment by rikmendes** [comment]
Works fine here. either from the Chrome extension OR the bookmarklet :)

**Comment by egoexpress** [comment]
@rikmendes: You don't have the Markdown plugin installed, do you?

**Comment by rikmendes** [comment]
Nope I don't...but I can try to disable them all and see if any of them is causing this...

**Comment by kylewm** [comment]
@egoexpress I installed the Markdown plugin, and yes confirm that the two plugins are incompatible. IMO, this is a bug in that plugin that it does not use the `body_id` parameter set here: https://github.com/kylewm/KnownReactions/blob/master/templates/default/entity/IdnoPlugins/Reactions/Like/edit.tpl.php#L54 (which is not surprisingly, I think that parameter was added since this plugin was written)

So there is no way for Repost to set the content of the text area programmtically.

**Comment by egoexpress** [comment]
Thanks for your test with the Markdown plugin and the error analysis. Seems I have to either drop the Markdown plugin or I'll try to open an issue in the Markdown plugin GitHub repo. I'll go without the Markdown plugin for now, proper-rendered Reactions are more important.
