### ISSUE TITLE
Pulled content brings wrong path to #hashtags (if any)

### ISSUE THREAD

**Issue by rikmendes** [kylewm/KnownReactions#13]
check out this repost : https://www.rmendes.net/2016/repost-of-putting-the-indieweb-into-context--f646984388

in fact check out any hashtags on my reposts : https://www.rmendes.net/content/reposts/ 

they all points to domain.tld/hashtag/ hence sending visitors to error pages. 
ex : https://www.rmendes.net/hashtag/Ireland?src=hash
![selection_008](https://cloud.githubusercontent.com/assets/12155003/16120358/856b3ea8-33df-11e6-921d-48844ee148fd.png)

@mentions included in the pulled content also points to my own domain but since they don't exist they bring visitors to error pages. ex: https://www.rmendes.net/2016/repost-of-putting-the-indieweb-into-context--f646984388

I guess this last issue is because the whole implementation is work in progress right ?

**Comment by kylewm** [comment]
I'm using https://github.com/indieweb/php-mf2-shim to get the content of social media sites. I guess the issue is that it returns relative URLs in the HTML of the tweet permalink. We could ask the library's maintainers to update it to return absolute URLs, or we could post process the result ourselves to fill in absolute URLs...

> I guess this last issue is because the whole implementation is work in progress right ?

I wouldn't say work-in-progress, more of a minimal first effort.

**Comment by rikmendes** [comment]
Can this https://github.com/indieweb/php-mf2-shim be used with Known ?

**Comment by kylewm** [comment]
I'm confused. That is the library this plugin uses.

**Comment by rikmendes** [comment]
Wow ok so If I'm using the plugin, I'm already using it...I thought it was
something you added to avoid partially the problem of relative links.

Ricardo Mendes
Internet & New Media Consultant / Social Media Manager
+32465915669
rick@rmendes.net
Mon CV :[image: www.ricardo-mendes.be]http://www.ricardo-mendes.be/
Mes liens : <http://twitter.com/RikMende> <http://twitter.com/EUwatchers>
<http://twitter.com/PolBegov> <https://www.facebook.com/euwatch>
<http://www.euwatch.eu/>
<https://www.linkedin.com/profile/view?id=221802511>

2016-06-17 18:52 GMT+02:00 Kyle Mahan <notifications@github.com>:
