### ISSUE TITLE
Warnings: cannot modify header information

### ISSUE THREAD

**Issue by raretrack** [kylewm/KnownReactions#18]
Hi

I have version 0.9.2 of Known hosted on [www.reclaimhosting.com](url); the server is running PHP version 5.5.38.

When I enable the Reactions plugin I get the following warning messages:
 
> Strict Standards: Declaration of Mf2\Shim\Twitter::parse() should be compatible with Mf2\Parser::parse($convertClassic = true, DOMElement $context = NULL) in /home/<snip>/public_html/<snip>/IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php on line 15
Warning: Cannot modify header information - headers already sent by (output started at /home/<snip>/public_html/<snip>/IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php:15) in /home/<snip>/public_html/<snip>/IdnoPlugins/IndiePub/Main.php on line 30
Warning: Cannot modify header information - headers already sent by (output started at /home/<snip>/public_html/<snip>/IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php:15) in /home/<snip>/public_html/<snip>/IdnoPlugins/IndiePub/Main.php on line 31
Warning: Cannot modify header information - headers already sent by (output started at /home/<snip>/public_html/<snip>/IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php:15) in /home/<snip>/public_html/<snip>/IdnoPlugins/IndiePub/Main.php on line 32
Warning: Cannot modify header information - headers already sent by (output started at /home/<snip>/public_html/<snip>/IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php:15) in /home/<snip>/public_html/<snip>/Idno/Common/Page.php on line 57
Warning: Cannot modify header information - headers already sent by (output started at /home/<snip>/public_html/<snip>/IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php:15) in /home/<snip>/public_html/<snip>/Idno/Common/Page.php on line 58
Warning: Cannot modify header information - headers already sent by (output started at /home/<snip>/public_html/<snip>/IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php:15) in /home/<snip>/public_html/<snip>/Idno/Core/Webmention.php on line 376
Warning: Cannot modify header information - headers already sent by (output started at /home/<snip>/public_html/<snip>/IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php:15) in /home/<snip>/public_html/<snip>/Idno/Core/Webmention.php on line 377
Warning: Cannot modify header information - headers already sent by (output started at /home/<snip>/public_html/<snip>/IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php:15) in /home/<snip>/public_html/<snip>/Idno/Core/PubSubHubbub.php on line 41
Warning: Cannot modify header information - headers already sent by (output started at /home/<snip>/public_html/<snip>/IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php:15) in /home/<snip>/public_html/<snip>/Idno/Core/PubSubHubbub.php on line 42
Warning: Cannot modify header information - headers already sent by (output started at /home/<snip>/public_html/<snip>/IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php:15) in /home/<snip>/public_html/<snip>/external/bonita/includes/Bonita/Templates.php on line 170
Warning: Cannot modify header information - headers already sent by (output started at /home/<snip>/public_html/<snip>/IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php:15) in /home/<snip>/public_html/<snip>/templates/default/shell.tpl.php on line 5
Warning: Cannot modify header information - headers already sent by (output started at /home/<snip>/public_html/<snip>/IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php:15) in /home/<snip>/public_html/<snip>/templates/default/shell.tpl.php on line 6

I'd be grateful if this can be looked into so I can successfuly get the plugin working for me. Many thanks.

**Comment by herbsmn** [comment]
Is this the first plugin you've installed or have other plugins worked? 

Might be a silly question, but is Known living in /home/public_html/ or is it in /home/public_html/Known?

I'm kind of a n00b, but i don't understand why it reads /home//public_html//IndoPlugins instead of /home/public_html/IdnoPlugins

**Comment by raretrack** [comment]
Thanks for your reply, herbsmn. 

I'm using a web hosting service; their path to my plugins directory is:
/home/[servername]/public_html/[siteURL]/IdnoPlugins/

Not sure what I did to end up posting // instead of the above, sorry about that!

I hadn't tried to install another plugin but have just had a go and installed two other community plugins OK.

**Comment by kylewm** [comment]
It sounds like maybe the Mf2/Shim (lives in this plugin) and Mf2 (lives in Known-core) libraries are out of sync with each other and their signatures are incompatible now -- Known has had a couple of releases since I worked on this plugin.

I can take a look at this later today or tomorrow.

**Comment by kylewm** [comment]
Oh btw, 

```
Strict Standards: Declaration of Mf2\Shim\Twitter::parse() should be compatible with Mf2\Parser::parse($convertClassic = true, DOMElement $context = NULL) in /home//public_html//IdnoPlugins/Reactions/external/mf2/shim/Mf2/Shim/Twitter.php on line 15
```

is the error; the rest (cannot modify headers) are just PHP complaining.

**Comment by kylewm** [comment]
As far as I can tell 

```
Strict Standards: Declaration of ...
```

is just a E_STRICT warning message but shouldn't cause any actual problems. Known outputs these as "notice" level messages to the log. In my apache conf, I have 

```
#
# LogLevel: Control the severity of messages logged to the error_log.
# Available values: trace8, ..., trace1, debug, info, notice, warn,
# error, crit, alert, emerg.
# It is also possible to configure the log level for particular modules, e.g.
# "LogLevel info ssl:warn"
#
LogLevel warn
```

so it never prints the notice messages.

To fix the actual problem, [php-mf2-shim](https://github.com/indieweb/php-mf2-shim) would need an update to be in sync with php-mf2.

**Comment by raretrack** [comment]
Thanks for looking into this, Kyle. 

Trouble is that the warnings are appearing on all of my Known pages on load - not just in the logs. Have tried logging out of Known, now the messages still appear but I can't log back into my site!

**Comment by kylewm** [comment]
Hmm, well, that happens because `display_errors` is On in /etc/php.ini -- it causes warnings and errors to be printed to the page instead of written to a log file.

It's a good setting for development, but in production, you probably want to turn it off.
