### ISSUE TITLE
Call to undefined function Mf2\\parse() 

### ISSUE THREAD

**Issue by danito** [kylewm/KnownReactions#3]
Hi,
I was trying to do a repost but I get this error:

> PHP Fatal error:  Call to undefined function Mf2\\parse() in /var/www/virtual/nxd4n/html/IdnoPlugins/Reactions/Pages/Fetch.php on line 29, referer: https://nxd4n.nixekinder.be/

I installed depedencies with composer : 

>  /home/nxd4n/html/IdnoPlugins/Reactions/vendor/mf2/mf2/Mf2/Parser.php

any idea?

**Comment by kylewm** [comment]
Are you using the latest version from git? There was a conflict with my version of Mf2 and the one used by Known core so I dropped it, and decided to stop using composer until it's adopted in core.

**Comment by danito** [comment]
Just git cloned it, renamed it to Ractions, but still the same error : 

> mod_fcgid: stderr: PHP Fatal error:  Call to undefined function Mf2\\parse() in /var/www/virtual/nxd4n/html/IdnoPlugins/Reactions/Pages/Fetch.php on line 29, referer: https://nxd4n.nixekinder.be/
[Tue Feb 16 21:07:12 2016] [warn] [client 141.135.57.184] mod_fcgid: stderr: Known (nxd4n.nixekinder.be): ERROR - Fatal Error: /var/www/virtual/nxd4n/html/IdnoPlugins/Reactions/Pages/Fetch.php:29 - "Call to undefined function Mf2\\parse()", on page nxd4n.nixekinder.be/reactions/fetch?url=http%3A%2F%2Fwirres.net%2Farticle%2Farticleview%2F9315%2F1%2F6%2F, referer: https://nxd4n.nixekinder.be/

This time I didn't run the composer.

**Comment by kylewm** [comment]
Hmm, yeah I guess the autoloader doesn't know to look in /Mf2/Parser.php to find the Mf2\parse() function. Hopefully fixed in 26eec5847e4ecef83026bca9cbb6afb9ed480c60

**Comment by danito** [comment]
after git pull:
>  PHP Fatal error:  Call to undefined function BarnabyWalters\\Mf2\\findMicroformatsByType() in /var/www/virtual/nxd4n/html/IdnoPlugins/Reactions/Pages/Fetch.php on line 32

should I run php composer.phar composer.lock?

**Comment by kylewm** [comment]
uh, that's weird. no it shouldn't be using composer at all. I'm really not sure what's going on or why your set up seems to be so different from mine.

You might double check that autoloader.php is being called, and that it adds entries to the loader for barnabywalters/mf-cleaner and mf2/shim

**Comment by kylewm** [comment]
oh wait, no it's the same issue as before -- Known's loader doesn't know where to look to load functions apparently...

**Comment by kylewm** [comment]
going to try going back to composer. thanks for bearing with me.

**Comment by kylewm** [comment]
Try updating again and run `composer install` in the plugin's directory

**Comment by danito** [comment]
works now :+1:
