### ISSUE TITLE
Missing argument 1 for saveDataFromInput() on Edit of a Repost

### ISSUE THREAD

**Issue by tinokremer** [kylewm/KnownReactions#4]
When editting an already saved "Repost", this error occurs:

[Wed Feb 17 13:48:51.556377 2016] [proxy_fcgi:error] [pid 1180:tid 139637502531328] [client 84.84.196.80:63655] AH01071: Got error 'PHP message: PHP Warning:  Missing argument 1 for IdnoPlugins\\Reactions\\Repost::saveDataFromInput(), called in /home/kremerti/domains/tinokremer.nl/public_html/Idno/Pages/Entity/View.php on line 112 and defined in /home/kremerti/domains/tinokremer.nl/public_html/IdnoPlugins/Reactions/Repost.php on line 24\nPHP message: PHP Notice:  Undefined variable: page in /home/kremerti/domains/tinokremer.nl/public_html/IdnoPlugins/Reactions/Repost.php on line 32\nPHP message: PHP Fatal error:  Call to a member function getInput() on null in /home/kremerti/domains/tinokremer.nl/public_html/IdnoPlugins/Reactions/Repost.php on line 32\nPHP message: Known (tinokremer.nl): ERROR - Fatal Error: /home/kremerti/domains/tinokremer.nl/public_html/IdnoPlugins/Reactions/Repost.php:32 - "Call to a member function getInput() on null", on page tinokremer.nl/2016/repost-of-smartphones-zijn-volgend-jaar-krachtiger-dan-spelcomputers--9c7cef972c\n', referer: https://tinokremer.nl/repost/edit/79a7f0464ef6ad93d35c0d332f453ab9

**Comment by kylewm** [comment]
Ew, thanks for the catch! I didn't realize saveDataFromInput was being called from other places. Should be fixed in 1df840f04dacb5d6bed0433bba9c2817c72a5145

I gave up on Composer for now, so you should be able to download/clone directly from github now.

**Comment by tinokremer** [comment]
Confirmed, I was already grabbing the github code directly for a while. You're the best!
