### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by georgkaser** [kylewm/KnownReactions#5]
Hi, I tried to install your plugin in my Known (Version: 0.9.1) - but the 0.1.3 Version and also the master is not working. The logfile says: "PHP Parse error:  syntax error, unexpected '=', expecting ')' in /var/www/html/known/IdnoPlugins/Reactions/Pages/Fetch.php on line 35"

Can you look what's the problem?

**Comment by kylewm** [comment]
@georgkaser Thanks for the report. Are you using PHP 5.4? I think there is an issue with using `empty()` on an expression in older versions of PHP -- should be an easy fix.

**Comment by georgkaser** [comment]
Ah, yes, I use PHP 5.4.

**Comment by kylewm** [comment]
hopefully fixed in 880aa0a40fd645733e7b30b44d677e8f10e3c79a

mind updating from git and checking?

**Comment by georgkaser** [comment]
Great, thank you - later I will try and give you a feedback.

**Comment by georgkaser** [comment]
Hmm, I tried. The good thing: I can install now and my Known is not white any more. But when I try to click on the like button, this error appeared: PHP Fatal error:  Can't use method return value in write context in /var/www/html/known/IdnoPlugins/Reactions/Like.php on line 58

Maybe I should make a PHP update :)

**Comment by georgkaser** [comment]
It seems to be incompatible with the bookmarks plugin - is it right? This is also not working now....

**Comment by kylewm** [comment]
It was not compatible with Bookmarks in the past, but as of 0.9.1 they should be compatible. I run both plugins without an issue as far as I can tell.

What's the symptom of Bookmarks not working?

**Comment by kylewm** [comment]
I really need to add some basic unit tests if for no other reason than to check compatibility with different PHP versions, but for now this should be fixed. Let me know!

**Comment by georgkaser** [comment]
;) It seems to be only a PHP 5.4 issue - with PHP 5.6 it works perfect (I tried on your blog ;)) Thank you very much. Your plugin should be standard in Known!
