### ISSUE TITLE
Unknown SSL protocol error using "Like" and "Repost" prevents posting

### ISSUE THREAD

**Issue by chrisaldrich** [kylewm/KnownReactions#8]
@petermolnar, Thanks for the mention of http://stream.boffosocko.com/2016/sharing-from-the-indieweb-on-mobile-android-with-apps-and on https://petermolnar.eu/press-this-indieweb/, glad you found it to be of use/interest.

I use both Known and WordPress for getting to know more about and actually using the indieweb, so I thought I’d mention that interestingly, I didn’t see a ping on the mention of my post (something which WordPress would have done automatically using a pingback) on Known. I’m hoping that perhaps as the indieweb grows, this type of cross-communication works itself out better, or that all URLs on all platforms default to using webmention.

Possibly more importantly, as you mention in the post that you monkeyed with some of your security settings, I wanted to let you know that I tried using Known (with KnownReactions installed) to “like” your post, but Known kicked back a security error that apparently wouldn’t allow it, indicating “Unknown SSL protocol error in connection to petermolnar.eu:443”.  [See also attached photo.] Typically Known would be querying your post to scrape the title from the post’s HTML to include as a description of what it is that I’m liking, so that I can then make the post to Known, which also thereby webmentions your post as well.

![pm screen cap](https://cloud.githubusercontent.com/assets/5882943/13730392/1c793824-e90b-11e5-9f46-8801478e6fad.PNG)

On the Known side, I’m not sure how often these errors pop up, but there should potentially be a way to manually fill in the description so that I can still make the post (clicking on the save button wouldn’t allow me to make the post).  I’m self-hosting the official version 0.9.1 which should have all of the updated plugins as of the last week (including [KnownReactions plugin](https://github.com/kylewm/KnownReactions) which may possibly be the piece preventing me from making the post, since it was a “like” after all). The issue was also replicated when attempting to “repost” (using KnownReactions) but not for “Share” or “Bookmarking” which are core Known functionalities.

I’m cross-post this to the KnownReactions and IDNO github repositories for potential follow up there as well.

**Comment by kylewm** [comment]
It sounds like the only way to fix the curl error is to upgrade libcurl. (This probably means that webmentioning petermolnar.eu will also fail)

> there should potentially be a way to manually fill in the description so that I can still make the post

Totally agree, thanks for the suggestion. Changed it in 0d26286d874d68ce39ed2b124b108ec1b3c42452 so that the title and description boxes will still appear, even if fetching the URL failed.

**Comment by chrisaldrich** [comment]
Thanks @kylewm. This seems to have done the trick to fix the issue. ([viz.](http://stream.boffosocko.com/2016/liked-extending-press-this-in-wordpress-to-support-indieweb-reply)) You've got my vote for including KnownReactions into IDNO core if you need it!

I would consider the postability portion of this as closed. As the alternate post regarding Peter's SSL issue on https://github.com/idno/Known/issues/1360 is still being discussed, I'll leave that one open for the moment.
